spring.application.name=QuackZone
spring.datasource.url=jdbc:mysql://localhost:3306/quackzone?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.security=DEBUG

node-service.url=${NODE_SERVICE_URL:http://localhost:4000}
email.logo-url=${EMAIL_LOGO_URL:http://localhost:8080/recursos/logoPagina.png}

